services:
  kafka:
    image: apache/kafka:latest
    env_file: .env
    ports:
      - "9092:9092"
      - "9093:9093"
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  default:
    driver: overlay